spring.application.name=CircuitBreakerExample
server.port=8080

# === CircuitBreaker Configuration ===
resilience4j.circuitbreaker.instances.externalService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.externalService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.externalService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.externalService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.externalService.slowCallDurationThreshold=3s
resilience4j.circuitbreaker.instances.externalService.slowCallRateThreshold=80
# === Timeout Configuration (!) ===
resilience4j.timelimiter.instances.externalService.timeoutDuration=3s

# === Actuator ===
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always


